matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    packages:
      #- qt5-default
      - libsqlite3-dev

before_install:
  - ./ci/travis/before_install_${TRAVIS_OS_NAME}.sh
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./ci/travis/brew_install_osx.sh; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi

script:
  # Add installed Qt path to $PATH
  - source qt-5.8.0.env
  - qmake -r
  - make -j2

